<?php
// config.php;
//20180407 km4ack
//edited 20180530 km4ack
//use this file to change the variables
//on the system. Only change what is
//between the ''. Be sure to leave the ''

//reminder to activate script
$reminder = 'DONT FORGET TO ACTIVATE MOVETOPAT IN CRON';

//login for admin control panel
$userlogin = 'admin';

//passwd for admin control panel
$userpasswd = 'admin';

//callsign of radio operator ALL UPPERCASE
//this is used for display purpose only
//this will not log you into the winlink system
$callsign = 'KM4ACK';

//Determines if replies are allowed into the system
//or not. Set to 0 (zero) for no replies. Set to 1 to
//allow replies into the system.
$replies = 1;

//footer to add to end of emails generated by the user if replies are allowed (condition set above)
$footer = 'Notice: This email was sent using amateur radio. Do not add attachments to replies. The system will not deliver replies with attachments. Also, this is not a private system. While we try to keep the replies private, it is possible that it could be viewed publicaly.';

//footer if replies are not allowed into the system (condition set above)
$footer1 = 'Due to limited resources, replies to this email are not allowed. This email was sent using amateur radio.';

//message visitor sees after submitting an email
//you will see this message if you compose and send
//an email using the system.
$visitmsg = 'Once reviewed, it will be sent over the air using amateur radio.';

//subject line of text messages sent from this system
//in a real event i would recommend 'EMERGENCY TEXT'
//to get the readers attention
$textsubject = 'Emergency Email Server Msg';

//DO NOT EDIT BELOW THIS LINE!!

//Set time DO NOT EDIT
//$time = date('Ymd--H:i',time());
$time = date('Y/m/d H:i',time());
//Get UTC DO NOT EDIT
$utc = gmdate('Y/m/d H:i',time());

?>
