#!/bin/bash

#setup additional folders needed for 
#the ees server
#20190325 km4ack

#create additional directories
#needed for EES server
mkdir -p /var/www/html/emails
mkdir -p /var/www/html/replies
chmod 777 /var/www/html/emails
chmod 777 /var/www/html/replies

#make movetopat exec
chmod +x movetopat
#make schedule exec
chmod +x schedule
#make autopostreply exec
chmod +x autopostreply

#create backup of config.php file
cp /var/www/html/config.php /var/www/html/config.php.org

#remove first run script
rm /var/www/html/firstrun

exit 0
