#!/bin/bash

#move files created by users of EES
#from /var/www/html/emails
#to your pat winlink out box for sending
#over the air.
#20180406 km4ack
#20190106 edited by kf7itf
#20211203 edited by KM4ACK
#20221223 edited by KQ4AFY
#script should be run by cron every
#minute.

# sets environment variables from pat
eval $(pat env)

CHECK=$(ls /var/www/html/emails/)

#check if files are in directory
if [ -z "$CHECK" ]
then
    #exit if files not found
    exit 0
else
    #move the files if found
    sudo mv /var/www/html/emails/*.b2f ${PAT_MAILBOX_PATH}/${PAT_MYCALL}/out/
fi

exit 0
