#!/bin/bash

#this is a test script to copy a file
#written with ghost writer from the 
#my docs folder to the web server
#This should be run by cron every minute
#20200229 km4ack

FILECHECK=$(diff ~/Documents/info.html /var/www/html/index.html)

#check file to see if it has changed. Copy if new
#Don't copy if no changes exist. This will save
#writes on the SD Card.
if [ -z "$FILECHECK" ]
then 
echo
else
touch $HOME/temp.html
cat /var/www/html/header > $HOME/temp.html
cat $HOME/Documents/info.html >> $HOME/temp.html
sudo cp $HOME/temp.html /var/www/html/index.html
rm $HOME/temp.html
fi
